spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pub_game?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update  # <--- CAMBIA DA validate A update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect # Opzionale, ma consigliato

server:
  port: 8080
  address: 0.0.0.0